### ISSUE TITLE
Can not disable verifyNonce when dealing with JWT claims

### ISSUE THREAD

**Issue by bghenne** [Drenso/symfony-oidc#28]
Hello,

I'm calling an Open ID Connect which does not provide "nonce" into JWT claims inside the token.
`Warning: Undefined property: stdClass::$nonce`

This does give me an error inside `OidcJwtHelper::verifyJwtClaims` method as it's  called through `OidcClient::authenticate` method without the possibility of specifying parameter `verifyNonce` to set it to `false`.

`   
 // Request and verify the tokens
    return $this->verifyTokens(
        $this->requestTokens('authorization_code', $code, $this->getRedirectUrl())
    );
`

So I dag a little bit and tried to create my own client but was not able to make it replace the default one.

I must say that I'm not particularly familiar with security stuffs into Symfony.
Can you please tell me what I'm doing wrong ?

Thanks.
Benjamin.

PS : Please find attached my configuration files.
[drenso_oidc.yaml.txt](https://github.com/Drenso/symfony-oidc/files/10373446/drenso_oidc.yaml.txt)
[security.yaml.txt](https://github.com/Drenso/symfony-oidc/files/10373447/security.yaml.txt)

**Comment by bobvandevijver** [comment]
The issue you have is because this bundle currently requires the nonce to be used and returned by the IdP. Replacing the complete client should be possible using the Symfony container by replacing the service id, but it is probably a lot easier to add an option to this bundle to disable the nonce completely. Would you be open to create a PR for that?

**Comment by bghenne** [comment]
There you have : https://github.com/Drenso/symfony-oidc/pull/30

Thank you.

**Comment by bobvandevijver** [comment]
Closed with #30.
