### ISSUE TITLE
How to use more clients in the same firewall ?

### ISSUE THREAD

**Issue by jirikmik** [Drenso/symfony-oidc#29]
Hello,  
please could you explain, how to use more clients with their check_paths in one firewall? I would like to distinguish what "response" is from where and so what to do in code. 
Thank you, J.

**Comment by bobvandevijver** [comment]
That would be something we do not support directly, also because Symfony does not support the usage of duplicate authenticator key (you also cannot use multiple `login_form` authenticators).

However, you could use this to create your own [custom authenticator](https://symfony.com/doc/current/security/custom_authenticator.html) which extends the `OidcAuthenticator` and is supplied the correct options. This would require some container configuration or a custom authenticator factory (the latter would be easiest), but it should be pretty straightforward. You can check the `OidcFactory` to see how the authenticator would be registered when using the `oidc` key in the firewall.

Another option would be to add support for multiple authenticator keys in this bundle, so you can register multiple instances under for example the `oidc_facebook` and `oidc_google` authenticator keys. This would require some additional configuration and dynamic factory registration, but should also be pretty straightforward.

**Comment by bobvandevijver** [comment]
I'm closing this as it is not an issue with this bundle.
