### ISSUE TITLE
How to retrieve user roles during the authentication ?

### ISSUE THREAD

**Issue by blixit** [Drenso/symfony-oidc#42]
Hello,
thank you for this library.

I'm seeking a way to retrieve the user roles during the authentication in the function `ensureUserExists` of the user provider. I noticed that `retrieveUserInfo()` does not return the field that contains roles. But I also noticed that the tokens returned by `authenticate()` contain these roles.

This is my question: Am I wrong trying to read tokens in the `ensureUserExists()` function ?

If I'm not, here is the solution I've in mind:
```php
// vendor/drenso/symfony-oidc-bundle/src/Security/OidcAuthenticator.php

public function authenticate(Request $request): Passport
  //...
  $authData = $this->oidcClient->authenticate($request);
  $userData = $this->oidcClient->retrieveUserInfo($authData);
  //...
  $this->oidcUserProvider->ensureUserExists($userIdentifier, $userData, $authData);
  // INSTEAD OF
  $this->oidcUserProvider->ensureUserExists($userIdentifier, $userData);
```

It's about one single parameter. Will you accept a Pull Request to add this parameter ? If not, could you please suggest me a way to get user roles the right way ?

Thanks in advance

**Comment by bobvandevijver** [comment]
Hmm, this feels similar to #37, where the user identifier was only placed in the ID token and not in the information as returned by the user info endpoint. If I read this correctly, there is a `roles` claim in the ID token that you want to access, right? And you are very sure that this information is not available in the user data as returned by the user info endpoint? Maybe it is something you can configure at the identity provider you're using?

If the data is indeed only available in the ID token, we will need to think of making it accessible. I am not very keen on changing the `ensureUserExists` method as you propose, as that would be a deprecation/BC-break that needs to be managed. I also prefer to not unconditionally forward the `OidcTokens` data, also because it contains both the access and ID token, and is actually still encoded.

What I do see as viable solution, is adding a configuration option which can take a specific configured claim value (or multiple claim values) and merge it with the `OidcUserData` object that is passed to the `ensureUserExists`. That way we introduce flexibility to forward anything required from the ID token (and already decode it before passing it), and keep the separation of concerns.

Would you be up for a PR? You can probably look at #38 for clues, it should contain something like:
  - A new array option which lists the claims from the ID token to be merged with the user data object
  - The implementation to retrieve the configured claims (and throw if not available?)
  - A way to merge this claim data into the merge data
  - Documentation

**Comment by blixit** [comment]
> Maybe it is something you can configure at the identity provider you're using?
It was actually a lack of configuration. I fixed up my provider configuration.

> Would you be up for a PR?
yes ! just for the exercice if you don't mind

**Comment by bobvandevijver** [comment]
Good to hear you were able to solve it using configuration at the provider.

Regarding the PR, I'm afraid that if it is not necessary to have in the bundle, it doesn't make sense to add it to be honest. Having what you need configured on the provider side it just a lot easier.
