### ISSUE TITLE
Unclear how to implement 'login_check' route

### ISSUE THREAD

**Issue by jasperweyne** [Drenso/symfony-oidc#5]
Currently, I'm trying to implement an OIDC client flow using this bundle. After following the steps provided in the readme, I've received an "Unable to generate a URL for the named route "login_check" as such route does not exist." error. After checking out the source code, it has become clear that the login_check route is used to verify the returned authorization code. However, this is step is currently undocumented.

**Comment by bobvandevijver** [comment]
`/login_check` is actually based on the default endpoint from the [Symfony framework](https://symfony.com/doc/current/reference/configuration/security.html#check-path).

> This is the route or path that your login form must submit to. The firewall will intercept any requests (POST requests only, by default) to this URL and process the submitted login credentials.

However, this bundle uses the `login_check` route name in order to generate the return route for the OIDC response. That's why the route must exists, but it can be any route if you override the default parameter of the OidcClient service (just add `$redirectRoute` with your route name to the `Drenso\OidcBundle\OidcClient` service definition).

I usually add something like this in order to be able to generate the route and have a fallback implementation for when the provider can't handle the request.

```php
/**
   * This route handles every login request
   * Only this route is listened to by the security services, so another route is not possible
   *
   * @Route("/login_check", name="login_check")
   * @IsGranted("IS_AUTHENTICATED_ANONYMOUSLY")
   */
  public function checkLogin(): RedirectResponse
  {
    if ($this->isGranted('IS_AUTHENTICATED_FULLY')) {
      return $this->redirect($this->generateUrl('homepage'));
    } else {
      return $this->redirect($this->generateUrl('login'));
    }
  }
```

I'll see if I can add this to the docs after you've confirmed this works for you 👍🏻

**Comment by jasperweyne** [comment]
Thanks for your swift response, this fixes the issue. I'm not explicitely using or providing the `login_check` parameter in my security config, this is probably related to the fact that I'm using a Guard authenticator instead of a `form_login`, which is structured not to use it.

**Comment by bobvandevijver** [comment]
Nah, that is because its the default value in the OidcClient constructor:

https://github.com/Drenso/symfony-oidc/blob/0f9ef051b99df1667228c720770f285bc064770e/src/OidcClient.php#L86

Even if you weren't using Guard but the more outdated methods this bundle uses, the route name wouldn't exist by default.

Anyways, somewhere in the (near) future we need to update this bundle to be able to work with Symfony 6 and the new authentication implementation anyways. For now, I will add a link to this issue in the documentation for when anyone else encounters this particular issue.
