### ISSUE TITLE
"No support for signature type: ES384"

### ISSUE THREAD

**Issue by axel37** [Drenso/symfony-oidc#53]
Hi, I couldn't find any issue mentionning this (nor could I find any info in the docs).

After succesfully setting up [Zitadel](https://zitadel.com/) with my app, for testing purposes, I'm trying to set up another provider, [Logto](https://logto.io/). 
When trying to log in, the following exception is thrown :

```
Drenso\OidcBundle\Security\Exception\OidcAuthenticationException
  #message: "No support for signature type: ES384"
  #file: ".../vendor/drenso/symfony-oidc-bundle/src/OidcJwtHelper.php&line=130#line130)"
```

While the error itself is pretty self-explanatory, the following is not :

- Is the absence of support an oversight / should it be treated as a work-in-progress ?
- If not, are we supposed to implement it ourselves (or use an existing third-party implementation) ? How ?

Thanks for reading, and thanks for the bundle 👍

**Comment by bobvandevijver** [comment]
This library has been based on https://github.com/jumbojett/OpenID-Connect-PHP, which did not support anything else than the algorithms that are supported now (RS256, RS384 & RS512). This means that the absence of support was intentional, and until now that never was an issue.

I believe it might be time to replace phpseclib/phpseclib with a library that is focused on JWT parsing, such as lcobucci/jwt (which is also used by the symfony mercure bundle for example). That will require a complete rewrite of the OidcJwtHelper class, but should resolve this issue...

**Comment by bobvandevijver** [comment]
@axel37 Can you check out the [jwt-validator](https://github.com/Drenso/symfony-oidc/tree/jwt-validator) branch? It adds support for ES signatures, but be aware that I did introduce some breaking changes (see [UPGRADE.md](https://github.com/Drenso/symfony-oidc/blob/jwt-validator/UPGRADE.md).

**Comment by bobvandevijver** [comment]
Closing this as [v3 ](https://github.com/Drenso/symfony-oidc/releases/tag/v3.0.0) has been released, which support ES signatures.
