### ISSUE TITLE
Store new token obtained after calling refresh token endpoint

### ISSUE THREAD

**Issue by bghenne** [Drenso/symfony-oidc#68]
Hi,

I'm using the refresh token method to get a new OidcTokens once the current access token is expired.

`$oidcTokens = $this->oidcClient->refreshTokens($this->refreshToken);`
`$this->tokenStorage->setToken($oidcTokens);`

But how can I store it in the TokenStorage ?

I've tried the `setToken` method but I got this error : 

![image](https://github.com/user-attachments/assets/20c29d56-9840-4533-be51-cacc4587412f)

Type does not match the expected.

What am I doing wrong ?

Thanks!

Using : PHP 8.3 / Symfony 7.1

**Comment by bobvandevijver** [comment]
You cannot directly store the `OidcTokens` in the Symfony security component because it is not meant for that, as the message you get clearly states. If you want to replace the token you can try creating an [`OidcToken`](https://github.com/Drenso/symfony-oidc/blob/c8a103fe3df6b92a9d1c4429eb6f64aba72fc15b/src/Security/Token/OidcToken.php) instead, but it is probably easier to just update the attribute of the current token:

```php
$this->tokenStorage->getToken()->setAttribute(OidcToken::AUTH_DATA_ATTR, $authData);
```

I believe the updated attributes should be stored correctly in the session when done like this, but you will need to try it in order to confirm.
