### ISSUE TITLE
Spring security framework ignores basic authentication requests

### ISSUE THREAD

**Issue by veldenb** [Drenso/symfony-oidc#73]
Spring security framework ignores basic authentication requests because a client_id is sent as a parameter without a secret.
I created a PR to fix the issue: https://github.com/Drenso/symfony-oidc/pull/72

**Comment by bobvandevijver** [comment]
According to the [RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1):

> A client MAY use the "client_id" request parameter to identify itself when sending requests to the token endpoint.

Which means that the current behaviour of this library is perfectly fine. You should file a bug with the Spring framework instead.

**Comment by veldenb** [comment]
@bobvandevijver then why is the implementation in v2.x exactly as I'm proposing for v1.x?
In v2.x the `client_id` is also removed: https://github.com/Drenso/symfony-oidc/blob/435e95c6f81328c009ddd798e6ef0603592bb66e/src/OidcClient.php#L420

**Comment by bobvandevijver** [comment]
I did not even notice you were targeting v1.x, so that's on me.

The spec still says "may", so it should be fine to keep it (and I know it was no problem for the provider we use), making it still the best to create the bug report at Spring. Having the client_id in the url allows for easy recognition in the IdP access logs for example.

In any case, having this equal to v2 is enough reason for me. I will be merging it in a minute.

**Comment by veldenb** [comment]
We planned the upgrade, but for now this helps us a lot.
And indeed, Spring should fix it at their side.

Thanks for reconsidering!
